name: Entrenar y Guardar Modelo de Maratón

on:
  push:
    branches:
      - main  # Ejecuta la acción cuando se hace un push a la rama principal
  schedule:
    - cron: '0 12 * * *'  # Ejecución diaria a las 12 PM (en UTC)

jobs:
  train-and-save-model:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Entrenar el modelo
        run: |
          python train_model.py

      - name: Guardar el modelo entrenado
        uses: actions/upload-artifact@v2
        with:
          name: marathon_prediction_model
          path: marathon_prediction_model.pkl  # Guardar el archivo del modelo entrenado como un artefacto

